// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.vigi.docs.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ro.vigi.docs.domain.DocumentTypeDataOnDemand;

privileged aspect DocumentTypeDataOnDemand_Roo_Configurable {
    
    declare @type: DocumentTypeDataOnDemand: @Configurable;
    
}
