// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.vigi.docs.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.vigi.docs.domain.DocumentType;
import ro.vigi.docs.domain.DocumentTypeDataOnDemand;
import ro.vigi.docs.repository.DocumentTypeRepository;
import ro.vigi.docs.service.DocumentTypeService;

privileged aspect DocumentTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DocumentTypeDataOnDemand: @Component;
    
    private Random DocumentTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<DocumentType> DocumentTypeDataOnDemand.data;
    
    @Autowired
    DocumentTypeService DocumentTypeDataOnDemand.documentTypeService;
    
    @Autowired
    DocumentTypeRepository DocumentTypeDataOnDemand.documentTypeRepository;
    
    public DocumentType DocumentTypeDataOnDemand.getNewTransientDocumentType(int index) {
        DocumentType obj = new DocumentType();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void DocumentTypeDataOnDemand.setDescription(DocumentType obj, int index) {
        String description = "description_" + index;
        if (description.length() > 250) {
            description = description.substring(0, 250);
        }
        obj.setDescription(description);
    }
    
    public void DocumentTypeDataOnDemand.setName(DocumentType obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = name.substring(0, 100);
        }
        obj.setName(name);
    }
    
    public DocumentType DocumentTypeDataOnDemand.getSpecificDocumentType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DocumentType obj = data.get(index);
        Long id = obj.getId();
        return documentTypeService.findDocumentType(id);
    }
    
    public DocumentType DocumentTypeDataOnDemand.getRandomDocumentType() {
        init();
        DocumentType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return documentTypeService.findDocumentType(id);
    }
    
    public boolean DocumentTypeDataOnDemand.modifyDocumentType(DocumentType obj) {
        return false;
    }
    
    public void DocumentTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = documentTypeService.findDocumentTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DocumentType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DocumentType>();
        for (int i = 0; i < 10; i++) {
            DocumentType obj = getNewTransientDocumentType(i);
            try {
                documentTypeService.saveDocumentType(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            documentTypeRepository.flush();
            data.add(obj);
        }
    }
    
}
